name: gamer
description: An app that reviews games.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # GUI
  cupertino_icons: ^1.0.4
  persistent_bottom_nav_bar: ^4.0.2
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^1.0.1
  material_floating_search_bar: ^0.3.6

  # Firebase
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  google_sign_in: ^5.2.2
  cloud_firestore: ^3.1.6
  json_annotation: ^4.4.0  # used for JSON serialization

  # Local File Access and Web Scraping
  web_scraper: ^0.1.4
  path_provider: ^2.0.8
  http: ^0.13.4

  # State Management
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # building JSON
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.3
  build_runner: ^2.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300